### ISSUE TITLE
How did you create the gif.h?

### ISSUE THREAD

**Issue by jhonnyx161** [bitbank2/bb_spi_lcd#4]
Hello
How did you create the gif.h?
regards

**Comment by jhonnyx161** [comment]
> Hello
> How did you create the gif.h?
> regards

**Comment by bitbank2** [comment]
I used my image_to_c tool:

https://github.com/bitbank2/image_to_c

**Comment by jhonnyx161** [comment]
> I used my image_to_c tool:
> 
> https://github.com/bitbank2/image_to_c
Thank you so much

how to connect
st7789 240*240 without cs pin and mini sd bb_spi_lcd

**Comment by bitbank2** [comment]
This question is beyond the scope of AnimatedGIF. I believe I have an example with that display in my bb_spi_lcd examples.

**Comment by jhonnyx161** [comment]
> Esta pregunta está más allá del alcance de AnimatedGIF. Creo que tengo un ejemplo con esa pantalla en mis ejemplos bb_spi_lcd.

the example is with adafruit. Adafruit is slower than bb_spi_lcd?

I see in the debb_spi_lcd.cpp code this if:
if (pLCD-> iLCDType == LCD_ST7789 || pLCD-> iLCDType == LCD_ST7789_240 || pLCD-> iLCDType == LCD_ST7789_135 || pLCD-> iLCDType == LCD_ST7789_NOCS)

I tried each one in spilcdInit () but with no positive results
am I missing something?
thanks for the support

**Comment by jhonnyx161** [comment]
> Esta pregunta está más allá del alcance de AnimatedGIF. Creo que tengo un ejemplo con esa pantalla en mis ejemplos bb_spi_lcd.

the example uses st7789 with cs pin, it is another model

the example with adafruit and st7735 is slower than bb_spi_lcd?

notice debb_spi_lcd.cpp code this if:
if (pLCD-> iLCDType == LCD_ST7789 || pLCD-> iLCDType == LCD_ST7789_240 || pLCD-> iLCDType == LCD_ST7789_135 || pLCD-> iLCDType == LCD_ST7789_NOCS)

I tried with each mode in spilcdInit () but got no positive results for st7789 if cs pin

thank you ppr the support

**Comment by bitbank2** [comment]
The correct choice is LCD_ST7789_NOCS. This is for the 240x240 display without an exposed CS pin. It needs the signal to be a phase of SPI mode 3.
