### ISSUE TITLE
'esp_lcd_i80_bus_config_t' has no non-static data member named 'psram_trans_align'

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/bb_spi_lcd#7]
.pio/libdeps/usb/bb_spi_lcd/src/bb_parallel.cpp:60:1: error: 'esp_lcd_i80_bus_config_t' has no non-static data member named 'psram_trans_align'

Probably same with `.sram_trans_align`

**Comment by bitbank2** [comment]
I'm using Arduino IDE 1.8.19 with ESP32 2.0.4 and I'm not seeing that error on any target MCUs. What versions of everything are you using?

**Comment by cyberman54** [comment]
I'm using ESP32 2.0.3, because with 2.0.4 currently LittleFS/SPIFFS is broken.

**Comment by cyberman54** [comment]
It compiles under 2.0.4, looks like the API was changed.
Since values psram_trans_align and sram_trans_align are not used by this lib, they could be commented out in the struct, this would safe backward compatibility.

**Comment by bitbank2** [comment]
ok, thanks for checking. I'll make the change.
