### ISSUE TITLE
Please add LilyGo T-Dongle S3 [LCD ST7735]

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/bb_spi_lcd#8]
see [description](https://github.com/Xinyuan-LilyGO/T-Dongle-S3)

Interface:
CS = 4
DC = 2
SPI CLK = 5
SPI MO/MI = 3
LED = 38
RST = 1

**Comment by bitbank2** [comment]
I assume you mean to add a "named display" entry for it. I don't own it and wasn't planning on buying it. I would need to test it before adding it as a named entry myself. You're welcome to do a pull request and add the changes. I would default the orientation to 90 degrees.

**Comment by bitbank2** [comment]
P.S. I'm not trying to discourage you from adding this. I would like you to add the info (quite simple) and test it since you have the board and I don't.
